In [ ]:
import torch
import torchaudio
import sys
from pathlib import Path

# adjust this to your repo root in the notebook environment
repo_root = Path("/teamspace/studios/this_studio/liquid-audio")
sys.path.insert(0, str(repo_root / "src"))

# avoid: from src.liquid_audio import ...
from liquid_audio.model.lfm2_audio import LFM2AudioModel
from liquid_audio.processor import LFM2AudioProcessor, ChatState
from liquid_audio.utils import LFMModality
from torchcodec.decoders import AudioDecoder

# Load models
HF_REPO = "LiquidAI/LFM2.5-Audio-1.5B"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
processor = LFM2AudioProcessor.from_pretrained(HF_REPO, device=device).eval()
# model = LFM2AudioModel.from_pretrained(HF_REPO, device=device).eval()

# Set up inputs for the model
chat = ChatState(processor)

chat.new_turn("system")
chat.add_text("Perform ASR.")
chat.end_turn()

chat.new_turn("user")
wav, sampling_rate = torchaudio.load("assets/asr.wav")


chat.add_audio(wav, sampling_rate)
chat.end_turn()

chat.new_turn("assistant")

print(chat.model_inputs)
for k, v in chat.items():
    print(k, v)

use_kernel_func_from_hub is not available in the installed kernels version. Please upgrade kernels to use this feature.


Fetching 14 files:   0%|          | 0/14 [00:00<?, ?it/s]

moving processor to device cpu and dtype None
audio processor is on device cpu and dtype torch.float32
torch.int64 text dtype
tensor([[[-1.5903, -1.5903, -1.5903,  ..., -1.4227, -1.3045,  0.0000],
         [-1.7043, -1.7043, -1.7043,  ..., -1.5859, -1.5075,  0.0000],
         [-1.4691, -1.4691, -1.4691,  ..., -1.4113, -1.3978,  0.0000],
         ...,
         [-1.1775, -1.1742, -1.1776,  ..., -0.8308, -0.9040,  0.0000],
         [-1.1951, -1.1945, -1.1939,  ..., -0.9471, -1.0030,  0.0000],
         [-1.2095, -1.2076, -1.2103,  ..., -0.9240, -1.0738,  0.0000]]])
torch.float32
torch.bfloat16
torch.bfloat16
['text', 'audio_in', 'audio_in_lens', 'audio_out', 'modality_flag']
text tensor([[    1,     6, 24131,   708,  8173,  1199, 11866,   559,   523,     7,
           708,     6,  6423,   708,     7,   708,     6, 64015,   708]])
audio_in tensor([[-1.5938, -1.5938, -1.5938,  ..., -1.4219, -1.3047,  0.0000],
        [-1.7031, -1.7031, -1.7031,  ..., -1.5859, -1.5078,  0.0000],
        [-1.4

In [2]:
print("hu")

hu


In [1]:
import torch
import torchaudio
from src.liquid_audio import LFM2AudioModel, LFM2AudioProcessor, ChatState, LFMModality
from torchcodec.decoders import AudioDecoder
audio_path = "assets/asr.wav"
# Load models
HF_REPO = "LiquidAI/LFM2.5-Audio-1.5B"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
processor = LFM2AudioProcessor.from_pretrained(HF_REPO, device=device).eval()
# model = LFM2AudioModel.from_pretrained(HF_REPO, device=device).eval()

# Set up inputs for the model
chat = ChatState(processor)

chat.new_turn("system")
chat.add_text("Perform ASR.")
chat.end_turn()

chat.new_turn("user")
wav, sampling_rate = AudioDecoder(audio_path, sample_rate=16000, num_channels=1).get_all_samples().data, 16000 #torchaudio.load("assets/asr.wav")


chat.add_audio(wav, sampling_rate)
chat.end_turn()

chat.new_turn("assistant")

print(chat.model_inputs)
for k, v in chat.items():
    print(k, v)

use_kernel_func_from_hub is not available in the installed kernels version. Please upgrade kernels to use this feature.


Fetching 14 files:   0%|          | 0/14 [00:00<?, ?it/s]

moving processor to device cpu and dtype None
audio processor is on device cpu and dtype torch.float32
torch.int64 text dtype
tensor([[[-1.5901, -1.5901, -1.5901,  ..., -1.4226, -1.3045,  0.0000],
         [-1.7041, -1.7041, -1.7041,  ..., -1.5858, -1.5074,  0.0000],
         [-1.4689, -1.4689, -1.4689,  ..., -1.4112, -1.3977,  0.0000],
         ...,
         [-1.1413, -1.1396, -1.1417,  ..., -0.7376, -0.8072,  0.0000],
         [-1.1404, -1.1403, -1.1399,  ..., -0.9087, -0.9303,  0.0000],
         [-1.1364, -1.1365, -1.1368,  ..., -0.9150, -1.0495,  0.0000]]])
torch.float32
torch.bfloat16 processor dtype
torch.bfloat16
['text', 'audio_in', 'audio_in_lens', 'audio_out', 'modality_flag']
text tensor([[    1,     6, 24131,   708,  8173,  1199, 11866,   559,   523,     7,
           708,     6,  6423,   708,     7,   708,     6, 64015,   708]])
audio_in tensor([[-1.5938, -1.5938, -1.5938,  ..., -1.4219, -1.3047,  0.0000],
        [-1.7031, -1.7031, -1.7031,  ..., -1.5859, -1.5078,  0.0000

In [2]:
audio_in = chat["audio_in"]
audio_in

tensor([[-1.5938, -1.5938, -1.5938,  ..., -1.4219, -1.3047,  0.0000],
        [-1.7031, -1.7031, -1.7031,  ..., -1.5859, -1.5078,  0.0000],
        [-1.4688, -1.4688, -1.4688,  ..., -1.4141, -1.3984,  0.0000],
        ...,
        [-1.1797, -1.1719, -1.1797,  ..., -0.8320, -0.9023,  0.0000],
        [-1.1953, -1.1953, -1.1953,  ..., -0.9453, -1.0000,  0.0000],
        [-1.2109, -1.2109, -1.2109,  ..., -0.9258, -1.0703,  0.0000]],
       dtype=torch.bfloat16)

In [3]:
audio_in.dtype

torch.bfloat16

In [2]:
chat.text

tensor([[    1,     6, 24131,   708,  8173,  1199, 11866,   559,   523,     7,
           708,     6,  6423,   708,     7,   708,     6, 64015,   708]])

In [3]:
chat.proc.text.decode(chat.text)

['<|startoftext|><|im_start|>system\nPerform ASR.<|im_end|>\n<|im_start|>user\n<|im_end|>\n<|im_start|>assistant\n']

In [ ]:
'<|startoftext|><|im_start|>system\nPerform ASR.<|im_end|>\n<|im_start|>user\n<|im_end|>\n<|im_start|>assistant\n'
'<|startoftext|><|im_start|>system\nPerform ASR.<|im_end|>\n<|im_start|>user\n<|im_end|>\n<|im_start|>assistant\n'

In [1]:
from transformers import AutoTokenizer

In [4]:
HF_REPO = "LiquidAI/LFM2.5-Audio-1.5B"


In [5]:
tok = AutoTokenizer.from_pretrained(HF_REPO)

In [6]:
tok.audio_token

AttributeError: TokenizersBackend has no attribute audio_token

In [2]:
torch.is_autocast_cpu_enabled()

/tmp/ipykernel_54761/3932608313.py:1: DeprecationWarning: torch.is_autocast_cpu_enabled() is deprecated. Please use torch.is_autocast_enabled('cpu') instead. (Triggered internally at /pytorch/torch/csrc/autograd/init.cpp:757.)
  torch.is_autocast_cpu_enabled()


False

Strategy

1. Find the example use cases in the main repo
    